export const characterInitialState = {
  id: null,
  name: "",
  class: "",
  level: null,
  attributes: {
    strength: null,
    dexterity: null,
    constitution: null,
    intelligence: null,
    wisdom: null,
    charisma: null,
  },
  armor: {
    slot1_name: "",
    slot1_defense: null,
    slot1_penalty: null,
    slot2_name: "",
    slot2_defense: null,
    slot2_penalty: null,
    defense_attribute: "DES",
    use_attribute: false,
    others: null,
  },
  skills: [],
  attacks: [],
};
